#! /bin/sh

sxhkd &

#bspc monitor -d Ichi Ni San IV V VI VII VIII IX X
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         5
bspc config window_gap          24

bspc config split_ratio		0.56
bspc config bottom_padding	0
bspc config borderless_monocle	true
bspc config gapless_monocle	true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#bspc config initial_polarity	longest_side

bspc config normal_border_color   $(awk NR==1 /home/chiya/.cache/wal/colors)
bspc config focused_border_color  $(awk NR==3 /home/chiya/.cache/wal/colors)
bspc config presel_border_color $(awk NR==5 /home/chiya/.cache/wal/colors)

#bspc config pointer_action1 move
#bspc config pointer_action2 none
#bspc config pointer_action3 resize_corner

bspc rule -a Krita desktop='^7' state=floating follow=on
bspc rule -a ranger desktop='^3' state=monocle follow=on focus=on
bspc rule -a Google-chrome desktop='^2' private=on
bspc rule -a Steam state=floating desktop='^7' center=true
bspc rule -a 'Pale moon' desktop='^2'
bspc rule -a TelegramDesktop desktop='^5' state=monocle
bspc rule -a Sxiv state=floating center=true
bspc rule -a mpv state=floating
bspc rule -a Zathura state=floating center=true
bspc rule -a "*" floating=on

