#! /bin/sh

sxhkd &

bspc monitor -d Ichi Ni San IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          24

bspc config split_ratio		0.56
bspc config bottom_padding	0
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
